name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
              java-version: '17'
              distribution: 'temurin'
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
